#!/bin/bash

clean () { 
    if [ -n "$READER_PID" ] && kill -0 "$READER_PID" 2> /dev/null;then
        kill "$READER_PID"
    fi
    }

trap clean EXIT

# Find pipes for the server
[ ! -z "$HOME" ] || HOME=$(realpath ~)
server_meta_dir="${HOME}/.asgsh"
if [ ! -d "${server_meta_dir}" ]; then
    echo "asgs is not running"
    exit 1
fi

pipein="${server_meta_dir}/pipein"
pipeout="${server_meta_dir}/pipeout"

# Outputs from the server
reader_out () {
    cat "${pipeout}" > /dev/tty
}

# Start the reader as background service so it prints continuously 
reader_out &
READER_PID=$!
# close_asgs is not internal to the server
echo "" > "${pipein}"
printf "\nTo exit without closing server run:\nclose_asgs" > "/dev/tty"

# Run user input
while true; do 
    read -r command
    if [[ $(echo "$command" | tr -d '[:space:]') == "close_asgs" ]];then
        break
    fi
    echo "$command" 
    if [[  $(echo "$command" | tr -d '[:space:]') == "exit" ]];then
        break
    fi
done > "${pipein}"
